module.exports = {
    MESSAGES: {
        USER_DATA_MISSING: "Data not found.",
        PROfILE_CREATED_SUCCESSFULLY: "Profile created successfully.",
        EMAIL_MISSING: "Email Id is missing.",
        ACCOUNT_CREATED_SUCCESSFULLY: "Account created successfully.",
        EMAIL_ALREADY_IN_USE: "Email Id already in use.",
        UPLOAD_SUCCESS: "Uploaded successfully.",
        INVALID_CREDENTIALS: "Invalid credentials.",
        LOGIN_SUCCESS: "Logged in successfully.",
        LOGOUT_SUCCESS: "Logged out successfully.",
        EMAIL_ALREADY_EXISTS: "Email already in use.",
        UPLOADING_ERROR: "Uploading error.",
        IMAGE_UPLOADED: "Image uploaded successfully.",
        PROFILE_UPDATED_SUCCESSFULLY: "Profile updated successfully.",
        PROFILE_DELETED_SUCCESSFULLY: "Profile deleted successfully.",
        ACCOUNT_NOT_FOUND: "Account doesn't exist.",
        PASSWORDS_SHOULD_BE_DIFFERENT: "New password should be different from the old password.",
        SUCCESS: "Success.",
        PASSWORD_RESET: "Password reset successfully.",
        DELETED_SUCCESSFULLY: "Deleted successfully.",
        UPDATED_SUCCESSFULLY : "Updated successfully.",
        SOMETHING_WENT_WRONG : "Something went wrong.",
        USER_NOT_VERIFIED: "User not verified.",
        USER_CREATED_SUCCESSFULLY : "User created successfully. ",
    },
};